# # Exercise 5A NumPy Fundamentals
# This notebook covers NumPy basics converting lists to 1D, 2D, and 3D arrays, inspecting data types (dtype), and manipulating shapes using the transpose attribute, indexing, and slicing.

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [14]:
print(arr_1.dtype)

# The result is <U6. 
# The '<' means little-endian.
# The 'U' means Unicode.
# The '6' means the longest word in the array has 6 characters.

<U6


In [6]:
# I use nested brackets for 2D arrays: [[row1], [row2]]
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
# Print the transposed version
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [10]:
print(arr_2)
# No, arr_2.T does not alter the original array. 
# It only shows a transposed view. The original variable remains the same.

[[10 11 12]
 [13 14 15]]


In [11]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [12]:
# Create arr_4 using the specific elements
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [13]:
# Shape (2, 2, 2) means 2 layers, 2 rows, 2 columns
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
