# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

 ## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop iterates through the rows of the 2D array so it prints entire 1D arrays (rows) multiplied by 2. The second loop goes deeper 
into the second dimension iterating through each individual number inside those rows and printing them one by one.

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
print(loop_result)

# Explanation
# This prints [28, 30, 32]. Because loop_result was assigned x * 2 it multiplied the entire current row (x) by 2 instead of the individual 
# number (y). Since it printed outside the loop I only see the result for the very last row processed.

[28 30 32]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# Error Message - ValueError - all input arrays must have the same shape
# Explanation  
# I cannot stack these arrays because they have different shapes. 
# joined_array_1 is 4x3 but joined_array_2 is 2x6. To stack arrays their dimensions must match exactly.

ValueError: all input arrays must have the same shape

In [14]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis=0)
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [17]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# Error message - ValueError 
# This fails because the row counts don't match. joined_array_1 has 4 rows but arrA only has 2 rows. I cannot glue them side-by-side (axis=1) 
# because the heights are different.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [18]:
# Horizontal Stack (glue side-by-side)
h_result = np.hstack((arrA, arrA))
print("hstack result:\n", h_result)
# Comment - hstack combines arrays horizontally (columns change, rows stay same).

# Vertical Stack (glue top-to-bottom)
v_result = np.vstack((arrA, arrA))
print("\nvstack result:\n", v_result)
# Comment - vstack combines arrays vertically (adds more rows).

# Depth Stack (stack like a deck of cards into 3D)
d_result = np.dstack((arrA, arrA))
print("\ndstack result:\n", d_result)
# Comment - dstack combines arrays along a third axis (depth) making a 3D array.

hstack result:
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

vstack result:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

dstack result:
 [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [19]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# Comment
# The result is a list containing 2 separate arrays. 
# Each of these new arrays has 2 dimensions with a shape of 2 rows and 3 columns.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [20]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# Comment 
# The result is a list containing 3 separate arrays. 
# Each array is still 2-dimensional. The first array has 2 rows while the remaining two arrays have 1 row each.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [21]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [22]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print("Sorted Array:\n", arrB_sorted)

Sorted Array:
 [[ 6  7]
 [ 5 13]
 [ 3  7]]


In [23]:
print("Original arrB:\n", arrB)

z = arrB < 7
arrC = arrB[z]

print("\nBoolean Mask z:\n", z)
print("\nFiltered arrC (values < 7):\n", arrC)

Original arrB:
 [[ 7  6]
 [13  5]
 [ 7  3]]

Boolean Mask z:
 [[False  True]
 [False  True]
 [False  True]]

Filtered arrC (values < 7):
 [6 5 3]


In [24]:
print("Original arrB:\n", arrB)

y = arrB >= 7
arrD = arrB[y]

print("\nBoolean Mask y:\n", y)
print("\nFiltered arrD (values >= 7):\n", arrD)

Original arrB:
 [[ 7  6]
 [13  5]
 [ 7  3]]

Boolean Mask y:
 [[ True False]
 [ True False]
 [ True False]]

Filtered arrD (values >= 7):
 [ 7 13  7]
