# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)
print("r_1:\n", r_1)

r_1:
 [ 9 18]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print("r_2:\n", r_2)

r_2:
 [[11 11]]


In [4]:
r_3 = np.random.random(size=(2, 1))
print("r_3:\n", r_3)

r_3:
 [[0.31749168]
 [0.07954949]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print("r_4:\n", r_4)

r_4:
 [[ 25  21  90  90  60]
 [ 31  95  68  69  95]
 [ 92  74  85  63 100]
 [ 74  60  54  57  84]]


In [6]:
r_5 = np.random.random(size=(4, 5))
print("r_5:\n", r_5)

r_5:
 [[0.29916079 0.99593582 0.64216849 0.58970202 0.75139507]
 [0.51274223 0.26852449 0.53468011 0.67998989 0.93611297]
 [0.56423586 0.11471064 0.51299058 0.88881808 0.87776921]
 [0.41389336 0.379478   0.91053182 0.73923058 0.09282217]]


## Generating Random Choices from an Array

In [8]:
students = np.array(['Alen', 'Biniam', 'Shafiqa', 'Daniel', 'Eleni', 'Filmon', 
                     'Grace', 'Hassan', 'Maya', 'Julia', 'Kevin', 'Lydia'])
print("Students Array:\n", students)

Students Array:
 ['Alen' 'Biniam' 'Shafiqa' 'Daniel' 'Eleni' 'Filmon' 'Grace' 'Hassan'
 'Maya' 'Julia' 'Kevin' 'Lydia']


In [9]:
call_on = np.random.choice(students)
print("Randomly Called On:", call_on)

Randomly Called On: Alen


In [11]:
breakout_groups = np.random.choice(students, size=(3, 4), replace=False)
print("Breakout Groups:\n", breakout_groups)

# Comment
# Yes, this is an effective way to assign breakout groups. 
# Setting replace=False ensures that every student gets placed into exactly one group of 4 without anyone being repeated or left out.

Breakout Groups:
 [['Alen' 'Maya' 'Eleni' 'Grace']
 ['Kevin' 'Biniam' 'Shafiqa' 'Daniel']
 ['Lydia' 'Hassan' 'Filmon' 'Julia']]


In [12]:
# p list must have exactly 12 values matching 12 students
probabilities = [0.0, 0.3, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07]

call_on_weighted = np.random.choice(students, size=5, p=probabilities)
print("Weighted Selections:", call_on_weighted)

# Explanation 
# I assigned a probability array p where Alen has a 0.0 (0%) chance of being picked,
# Biniam has a 0.3 (30%) chance and the remaining 10 students split the remaining 70% evenly (0.07 or 7% each). The entire list totals 1.0.

Weighted Selections: ['Biniam' 'Biniam' 'Eleni' 'Biniam' 'Filmon']


## Generating a Normal Distribution

In [14]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[14.60926323 15.39128796 23.02166732 13.40143336  3.46807394]
 [12.79102766  7.07068006  9.6085249  10.94996516 12.43755697]
 [ 9.8902616  14.64092058  6.88050918 16.81891801  6.03353855]
 [-0.67671569  5.28283822  6.88743167  7.79199084 10.32944614]]
