# Exercise 1.C Performing operations on arrays

In [1]:
 import numpy as np

## Sample Arrays

In [2]:
# Re-creating variables r_1 through r_5 from Exercise 1.B
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

print("r_1:\n", r_1)
print("\nr_2:\n", r_2)
print("\nr_3:\n", r_3)
print("\nr_4:\n", r_4)
print("\nr_5:\n", r_5)

r_1:
 [12 18]

r_2:
 [[14 12]]

r_3:
 [[0.54828383]
 [0.05210411]]

r_4:
 [[92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]
 [62 87 86 61 40]]

r_5:
 [[0.10375738 0.16113159 0.71207146 0.91659572 0.11135662]
 [0.94322927 0.25268422 0.53715809 0.46779086 0.76813079]
 [0.62371622 0.65550955 0.82372423 0.43676448 0.41799562]
 [0.93455028 0.39991353 0.42880431 0.59374926 0.02457274]]


## Permutations

In [3]:
# 1. Print current value of r_4
print("Original r_4:\n", r_4)

Original r_4:
 [[92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]
 [62 87 86 61 40]]


In [4]:
# 2. Shuffle r_4 and print again
np.random.shuffle(r_4)
print("\nShuffled r_4:\n", r_4)


Shuffled r_4:
 [[62 87 86 61 40]
 [92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]]


In [5]:
# When np.random.shuffle() is applied to a two-dimensional array like r_4, it only shuffles the array along its first axis (axis=0). This means the 
#rows themselves changed their order but the individual numbers inside each row stayed exactly the same and moved together.

In [6]:
# 4. Create new_shuffle using permutation
new_shuffle = np.random.permutation(r_4)

print("new_shuffle (Permutation Result):\n", new_shuffle)
print("\nr_4 (Original Array after permutation):\n", r_4)

new_shuffle (Permutation Result):
 [[81 78 25 21 87]
 [50 90 93 45 56]
 [62 87 86 61 40]
 [92 37 58 50 61]]

r_4 (Original Array after permutation):
 [[62 87 86 61 40]
 [92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]]


In [7]:
## When to use Shuffle vs. Permutation

# Use np.random.shuffle() when I want to save computer memory and It does not matter to keeping the original order of my dataset. It 
# overwrites the data directly.
# Use np.random.permutation() when I need to keep my original dataset safe and unchanged because it outputs a brand new copy.

## Mathematical Operations

In [8]:
print("r_1:\n", r_1, "Shape:", r_1.shape)
print("r_2:\n", r_2, "Shape:", r_2.shape)

# Adding r_1 and r_2
result_1_2 = np.add(r_1, r_2)
print("\nResult (r_1 + r_2):\n", result_1_2)
print("Result Shape:", result_1_2.shape)

r_1:
 [12 18] Shape: (2,)
r_2:
 [[14 12]] Shape: (1, 2)

Result (r_1 + r_2):
 [[26 30]]
Result Shape: (1, 2)


In [9]:
print("r_1:\n", r_1, "Shape:", r_1.shape)
print("r_3:\n", r_3, "Shape:", r_3.shape)

# Adding r_1 and r_3
result_1_3 = np.add(r_1, r_3)
print("\nResult (r_1 + r_3):\n", result_1_3)
print("Result Shape:", result_1_3.shape)

r_1:
 [12 18] Shape: (2,)
r_3:
 [[0.54828383]
 [0.05210411]] Shape: (2, 1)

Result (r_1 + r_3):
 [[12.54828383 18.54828383]
 [12.05210411 18.05210411]]
Result Shape: (2, 2)


In [10]:
print("r_2:\n", r_2, "Shape:", r_2.shape)
print("r_4:\n", r_4, "Shape:", r_4.shape)

# Adding r_2 and r_4
result_2_4 = np.add(r_2, r_4)
print("\nResult (r_2 + r_4):\n", result_2_4)
print("Result Shape:", result_2_4.shape)

r_2:
 [[14 12]] Shape: (1, 2)
r_4:
 [[62 87 86 61 40]
 [92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]] Shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [12]:
# 1. Expression to illustrate adding r_1 and r_4
np.add(r_1, r_4)
# error message
# ValueError: operands could not be broadcast together with shapes (2,) (4,5)

# 2. What happens when adding r_2 to r_4?
np.add(r_2, r_4)
# Error message - ValueError operands could not be broadcast together with shapes (1,2) (4,5)

# 3. What happens when adding r_3 to r_4?
np.add(r_3, r_4)
# Error message: ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

# My Findings Comment
# All three combinations fail and give a ValueError. 
# For r_1 and r_2, their column size 2 does not match r_4's column size 5. 
# For r_3, even though its 1 column can stretch to match 5 columns its row size 2 does not match r_4's row size 4, so they cannot broadcast together.

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [13]:
# Create the small array and add it to r_4
small_array_1 = np.array([1])
result_small_1 = np.add(r_4, small_array_1)

# Print the result
print("Result of r_4 + np.array([1]):")
print(result_small_1)

Result of r_4 + np.array([1]):
[[63 88 87 62 41]
 [93 38 59 51 62]
 [51 91 94 46 57]
 [82 79 26 22 88]]


In [14]:
# Create the 2D small array and add it to r_4
small_array_2 = np.array([[1]])
result_small_2 = np.add(r_4, small_array_2)

# Print the result
print("Result of r_4 + np.array([[1]]):")
print(result_small_2)

Result of r_4 + np.array([[1]]):
[[63 88 87 62 41]
 [93 38 59 51 62]
 [51 91 94 46 57]
 [82 79 26 22 88]]


In [15]:
# Create the 1D array with 5 elements and add it to r_4
row_array = np.array([1, 1, 1, 1, 1])
result_row = np.add(r_4, row_array)

# Print the result
print("Result of r_4 + np.array([1,1,1,1,1]):")
print(result_row)

Result of r_4 + np.array([1,1,1,1,1]):
[[63 88 87 62 41]
 [93 38 59 51 62]
 [51 91 94 46 57]
 [82 79 26 22 88]]


In [11]:
# Try to add the array to r_4 
np.add(r_4, np.array([[1], [1]]))

# Comment with the error message
# ValueError - operands could not be broadcast together with shapes (4,5) (2,1)

ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

## How NumPy Broadcasting Works

How it works Broadcasting allows NumPy to do math on arrays of different sizes. It automatically stretches the smaller array so it matches the shape of the larger one.

What gets added to - what NumPy adds numbers element by element. If you add a single number [1] to a large array, that 1 gets added to every single individual number inside the large array.

What determines the final shape - The final shape takes the maximum size of the two arrays along each dimension (rows and columns) after the smaller dimensions of 1 are stretched to match the larger ones.


# Rounding

In [26]:
# Print starting values of r_3
print("Original r_3 values")
print(r_3)

Original r_3 values
[[0.54828383]
 [0.05210411]]


In [27]:
# Round using trunc 
trunc_result = np.trunc(r_3)
print("Truncated values")
print(trunc_result)

Truncated values
[[0.]
 [0.]]


In [28]:
# Round using fix 
fix_result = np.fix(r_3)
print("Fixed values")
print(fix_result)

Fixed values
[[0.]
 [0.]]


In [29]:
# Round using floor 
floor_result = np.floor(r_3)
print("Floored values")
print(floor_result)

Floored values
[[0.]
 [0.]]


In [25]:
# Round using ceil
ceil_result = np.ceil(r_3)
print("Ceiled values")
print(ceil_result)

Ceiled values
[[1.]
 [1.]]


In [24]:
# Round to 2 decimal places
round_result = np.round(r_3, decimals=2)
print("Rounded to 2 decimal places")
print(round_result)

Rounded to 2 decimal places
[[0.55]
 [0.05]]


 ## Cumulative Operations

In [30]:
# Print starting values of r_4
print("Original r_4 values")
print(r_4)

Original r_4 values
[[62 87 86 61 40]
 [92 37 58 50 61]
 [50 90 93 45 56]
 [81 78 25 21 87]]


In [31]:
# Sum of all vallue
total_sum = np.sum(r_4)
print("Sum of all values")
print(total_sum)

Sum of all values
1260


In [33]:
# Sum down the columns 
sum_axis_0 = np.sum(r_4, axis=0)
print("Sum along axis 0")
print(sum_axis_0)

Sum along axis 0
[285 292 262 177 244]


In [34]:
# Sum across the rows 
sum_axis_1 = np.sum(r_4, axis=1)
print("Sum along axis 1")
print(sum_axis_1)

Sum along axis 1
[336 298 334 292]


In [36]:
# rolling total of all numbers
cumsum_flat = np.cumsum(r_4)
print("Cumulative sum")
print(cumsum_flat)

Cumulative sum
[  62  149  235  296  336  428  465  523  573  634  684  774  867  912
  968 1049 1127 1152 1173 1260]


In [37]:
# Rolling total adding down each column
cumsum_axis_0 = np.cumsum(r_4, axis=0)
print("Cumulative sum along axis 0")
print(cumsum_axis_0)

Cumulative sum along axis 0
[[ 62  87  86  61  40]
 [154 124 144 111 101]
 [204 214 237 156 157]
 [285 292 262 177 244]]


## Grocery Problem

In [39]:
# Order of categories [Vegetables, Fruits, Snacks, Beverages]
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("bag1 contents:", bag1)
print("bag2 contents:", bag2)

bag1 contents: [2 3 4 0]
bag2 contents: [4 0 1 2]


In [40]:
# Calculate the total items for each bag using sum
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)

# Print the result 
print(f"The first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [41]:
# Add the bags together to get totals by category
category_totals = np.add(bag1, bag2)

# Extract each category from the total array
veggies = category_totals[0]
fruits = category_totals[1]
snacks = category_totals[2]
drinks = category_totals[3]

# Print the result
print(f"There are {veggies} vegetables, {fruits} fruits, {snacks} boxes of snacks, and {drinks} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [47]:
# Create an array for Ali's knocks (Mon to Fri)
ali = np.array([5, 4, 6, 4, 2])
print("Ali's knocks", ali)

Ali's knocks [5 4 6 4 2]


In [46]:
# Create an array for Ben's knocks (0 on Monday because he was out of town)
ben = np.array([0, 5, 5, 3, 4])
print("Ben's knocks", ben)

Ben's knocks [0 5 5 3 4]


In [45]:
# Create an array for Carla's knocks (0 on Wednesday because she was sick)
carla = np.array([3, 6, 0, 3, 4])
print("Carla's knocks", carla)

Carla's knocks [3 6 0 3 4]


In [48]:
# Compile all three individual arrays into a single array
all_knocks = np.array([ali, ben, carla])
print("all_knocks array")
print(all_knocks)

all_knocks array
[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [49]:
# Calculate total for each person and the collective grand total
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print("Totals by person (Ali, Ben, Carla):", person_totals)
print("Collective group total:", group_total)

Totals by person (Ali, Ben, Carla): [21 17 16]
Collective group total: 54


In [52]:
# 1. Get the total knocks for the group day by day 
daily_group_knocks = np.sum(all_knocks, axis=0)

# 2. Get the rolling total (cumulative sum) day by day
rolling_knocks = np.cumsum(daily_group_knocks)

# 3. Multiply by 0.5 to get estimated votes (2 knocks = 1 vote)
rolling_votes = rolling_knocks * 0.5

print("Rolling total of estimated votes day by day (Mon-Fri)")
print(rolling_votes)

Rolling total of estimated votes day by day (Mon-Fri)
[ 4.  11.5 17.  22.  27. ]
